# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 19809134f012c8f2817f80e429549c6fc04805c047eed9f835da17978dc65e9775583084f0ca2547ea02e319b123bd911123a65fb79d856dee8a6981fbab34de

test:
  secret_key_base: f076d4b61a19b12c97a460073c59711669daeda256559ab913599b9b78ea243d633d02c2892971459767563a038713db737e5ee1f9e66f5d62896655da481082

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
